# https://linux.die.net/man/5/avahi-daemon.conf

[server]
# Enforce no other avahi on the same ip: turn this to yes
disallow-other-stacks=no
# Network
use-ipv4=yes
use-ipv6=yes
# Just testing
# allow-interfaces=eth0,eno1,wlan0
# Dbus
enable-dbus=yes
# Rate limiting
ratelimit-interval-usec=1000000
ratelimit-burst=1000

[wide-area]
enable-wide-area=yes

[publish]
# Publishing?
disable-publishing=no
disable-user-service-publishing=no
publish-addresses=yes
# OS information stfu
publish-hinfo=no
# sure...
publish-workstation=no
# Publish ipv4 address over ipv6
publish-a-on-ipv6=no
# And conversely
publish-aaaa-on-ipv4=no

[rlimits]
rlimit-core=0
rlimit-data=4194304
rlimit-fsize=0
rlimit-nofile=100
rlimit-stack=4194304
# Remove this, according to https://github.com/lxc/lxc/issues/25
# rlimit-nproc = 3
